name:  perf test jmeter
on: [push]
jobs:
  perf-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run JMeter Tests
        uses: rbhadti94/apache-jmeter-action@v0.3.1
        with:
          testFilePath: jmeter/jmeter-example.jmx
          outputReportsFolder: reports/
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: reports/